name: machine-teaching
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.7,<3.10
  - pip
  - numpy
  - pandas
  - nltk
  - jupyterlab
  - tqdm
  - scikit-learn
  - imbalanced-learn
  - textblob
  - snorkel
  - spacy
  - spacy-model-en_core_web_sm
  - matplotlib
  - pytorch
  - tensorboardx
  - pip:
    - snorkel-metal
    