name: machine-teaching
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.7,<3.10
  - pip
  - numpy
  - pandas
  - nltk
  - textblob
  - jupyterlab
  - tqdm
  - scikit-learn
  - snorkel
  - spacy
  - matplotlib
  - pytorch
