name: motion-classification-37
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python==3.7
  - pip
  - numpy
  - pandas
  - nltk
  - jupyterlab
  - tqdm
  - transformers==4.1.1
  - scikit-learn
  - imbalanced-learn
  - snorkel
  - matplotlib
  - pytorch
  - tensorboardx
  - pip:
    - snorkel-metal
    