name: motion-classification
channels:
  - anaconda
  - conda-forge
  - pytorch
  - huggingface
  - defaults
dependencies:
  - python>=3.8,<3.9
  - pip
  - numpy
  - pandas
  - nltk
  - jupyterlab
  - tqdm
  - scikit-learn
  - imbalanced-learn
  - snorkel
  - spacy
  - black
  - spacy-model-en_core_web_sm
  - matplotlib
  - pytorch
  - tensorboardx
  - pip:
    - snorkel-metal
    - transformers
    - fsspec
    